gText_Birch_Welcome::
	.string "Greetings! Welcome to the expedition!\p"
	.string "My name is CYCAD.\p"
	.string "I'm the lead paleontologist overseeing\n"
	.string "the exploration of this uncharted land.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This primeval creature is what\n"
	.string "we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This forgotten realm has slumbered\n"
	.string "beneath time for millions of years.\p"
	.string "Here, creatures from Earth's ancient\n"
	.string "dawn thrive just as they did in the\l"
	.string "prehistoric epoch.\p"
	.string "Colossal titans walk the earth, ancient\n"
	.string "fliers rule the skies, and primeval\l"
	.string "leviathans prowl the deep waters.\p"
	.string "We researchers explore alongside them,\n"
	.string "studying their boundless power and\l"
	.string "unraveling the origin of all species.\p"
	.string "To unlock the secrets of our past,\n"
	.string "we pioneers must forge ahead!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And which Research Fellow are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you LEO?\n"
	.string "Or are you MAYA?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Excellent!\p"
	.string "You're {PLAYER}{KUN}, our newly appointed\n"
	.string "Research Fellow at CAMP AMBERVALE!\l"
	.string "I've been eager to have you here!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Tell me, are you ready?\p"
	.string "An untamed world of primeval wonder\n"
	.string "and ancient mysteries awaits us.\p"
	.string "Steel your courage and step forth into\n"
	.string "the dawn of POKéMON history!\p"
	.string "Come find me at the excavation site in\n"
	.string "CAMP AMBERVALE. Let's begin!\p"
	.string "$"
